using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    // Set variabes
    public float mouseSensitivity = 100f;

    public Transform playerBody;

    float xRotation = 0f;

    // Start is called before the first frame update
    void Start()
    {
        // Locks cursor so when you move the cursor you don't see it.
        Cursor.lockState = CursorLockMode.Locked;
    }

    // Update is called once per frame
    void Update()
    {
        // Get Mouse imput on the x and y axis and set as variable
        float mouseX = Input.GetAxis("Mouse X") * mouseSensitivity * Time.deltaTime;
        float mouseY = Input.GetAxis("Mouse Y") * mouseSensitivity * Time.deltaTime;

        // Assign a new value every update to xRtation according to mouseY
        xRotation -= mouseY;
        // Clamp the value of xRotation between -90 and 90 degrees stops player from turning the camera too far up or down.
        xRotation = Mathf.Clamp(xRotation, -90f, 90f);
        // rotate player and camera on the axis
        transform.localRotation = Quaternion.Euler(xRotation, 0f, 0f);
        playerBody.Rotate(Vector3.up * mouseX);
    }
}
